### ISSUE TITLE
Thanks for sharing!

### ISSUE THREAD

**Issue by Max-Meng** [FlexMonkey/SnapSwift#2]
Thanks for sharing!
But, what's the purpose to include the SnapSwiftScreenRecording.gif file in the package?
while its size is 24MB large.

PS. I actually want to leave a comments, but I can't find such a feature, sorry if this shouldn't be here.

**Comment by FlexMonkey** [comment]
Hi,

Thanks very much for your comment. The .gif is there for the GitHub readme - just so everything is packaged up neatly.

If it's causing you problems, I can host elsewhere :)

Best wishes,

Simon

**Comment by Max-Meng** [comment]
Thanks for the reply..
No, there is no problem for me. I just wandering if I can safely removed it if I need to use your code.
And I didn't noticed it is animatable until you tell me so and then I opened it in Safari.
So, problem solved!

Thanks again!

**Comment by FlexMonkey** [comment]
Great stuff. You only need a few files to get up and running: https://github.com/FlexMonkey/SnapSwift#installation

Have fun using it, I'd love to know how you get on.

Cheers,

Simon
